# Twitter handles/common airline names
airline_names = [
    "all nippon",
    "ek",
    "jal",
    "garuda",
    "virgin",
    "emiratessupport",
    "klm_uk",
    "etihadairways",
    "lufthansa_de",
    "airsalesforce",
    "americanair",
    "british_airways",
    "etihadhelp",
    "virginaustralia",
    "lufthansa_usa",
    "lufthansa_india",
    "southwestair",
    "aircanada",
    "kenyaairways",
    "airfrance",
    "turkish",
    "evaairus",
    "alaskaair"
    "qatarairways",
    "united air",
    "united",
    "united airlines",
    "united arab",
    "united arab emirates",
    "singapore",
    "unitedairlines",
    "singapore air",
    "singapore airlines",
    "singaporeair",
    "singaporeairlines",
    "cathaypacific",
    "britishairways",
    "flyemirates",
    "emiratesairlines",
    "klm100",
    "sq",
    "emirates",
    "ek",
    "flyana_official",
    "all nippon air",
    "all nippon airways",
    "ana",
    "qatar air",
    "qatar airways",
    "qatar",
    "qr",
    "etihad",
    "ey",
    "cathay",
    "cx",
    "cathay pacific",
    "lufthansa",
    "lh",
    "ba",
    "british air",
    "british airways",
    "thai air",
    "thai airways",
    "thai",
    "tg",
    "air new zealand",
    "airnz",
    "flyairnz",
    "scoot",
    "flyscoot",
    "qantas",
    "klm",
    "korean air",
    "ke",
    "korean air lines",
    "korean airlines",
    "asiana",
    "oz",
    "china air",
    "china airlines",
    "ci",
    "jetblue",
    "b6",
    "eva air",
    "br",
    "eva airways",
    "delta",
    "dl",
    "delta air",
    "delta air lines",
    "delta airlines",
    "uae",
    "sia",
    "klm_eir",
    # "arabia ?united",
    "saudi arabia",
    "dubklm100",
    "american",
    "aa",
    "southwest",
    "wn",
    "spirit"
]

# Mapping of Twitter handle/common names of airlines to actual airline names
airline_synonyms = {
    "flyana_official": "All Nippon Airway",
    "all nippon": "All Nippon Airway",
    "jal": "Japan Airlines",
    "garuda": "Garuda",
    "turkish": "Turkish Airlines",
    "virgin": "Virgin Atlantic",
    "emiratessupport": "Emirates Airline",
    "klm_uk": "KLM Airlines",
    "etihadairways": "Etihad Airways",
    "lufthansa_de": "Lufthansa",
    "airsalesforce": "Singapore Airlines",
    "americanair": "American Airlines",
    "british_airways": "British Airways",
    "etihadhelp": "Etihad Airways",
    "virginaustralia": "Virgin Australia",
    "lufthansa_usa": "Lufthansa",
    "lufthansa_india": "Lufthansa",
    "southwestair": "Southwest",
    "aircanada": "Air Canada",
    "kenyaairways": "Kenya Airways",
    "airfrance": "Air France",
    "evaairus": "Eva Airways",
    "alaskaair": "Alaska Airlines",
    "qatarairways": "Qatar Airways",
    "united air": "United Airlines",
    "united": "United Airlines",
    "united airlines": "United Airlines",
    "united arab": "Emirates Airline",
    "united arab emirates": "Emirates Airline",
    "singapore": "Singapore Airlines",
    "unitedairlines": "United Airlines",
    "singapore air": "Singapore Airlines",
    "singapore airlines": "Singapore Airlines",
    "singaporeair": "Singapore Airlines",
    "singaporeairlines": "Singapore Airlines",
    "cathaypacific": "Cathay Pacific Airways",
    "britishairways": "British Airways",
    "flyemirates": "Emirates Airline",
    "emiratesairlines": "Emirates Airline",
    "klm100": "KLM Airlines",
    "sq": "Singapore Airlines",
    "emirates": "Emirates Airline",
    "ek": "Emirates Airline",
    "all nippon air": "All Nippon Airway",
    "all nippon airways": "All Nippon Airway",
    "ana": "All Nippon Airway",
    "qatar air": "Qatar Airways",
    "qatar airways": "Qatar Airways",
    "qatar": "Qatar Airways",
    "qr": "Qatar Airways",
    "etihad": "Etihad Airways",
    "ey": "Etihad Airways",
    "cathay": "Cathay Pacific Airways",
    "cx": "Cathay Pacific Airways",
    "cathay pacific": "Cathay Pacific Airways",
    "lufthansa": "Lufthansa",
    "lh": "Lufthansa",
    "ba": "British Airways",
    "british air": "British Airways",
    "british airways": "British Airways",
    "thai air": "Thai Airways",
    "thai airways": "Thai Airways",
    "thai": "Thai Airways",
    "tg": "Thai Airways",
    "air new zealand": "Air New Zealand",
    "airnz": "Air New Zealand",
    "flyairnz": "Air New Zealand",
    "scoot": "Scoot Tigerair",
    "flyscoot": "Scoot Tigerair",
    "qantas": "Qantas Airways",
    "klm": "KLM Airlines",
    "korean air": "Korean Air",
    "ke": "Korean Air",
    "korean air lines": "Korean Air",
    "korean airlines": "Korean Air",
    "asiana": "Asiana Air",
    "oz": "Asiana Air",
    "china air": "China Airlines",
    "china airlines": "China Airlines",
    "ci": "China Airlines",
    "jetblue": "Jetblue Airways",
    "b6": "Jetblue Airways",
    "eva air": "Eva Airways",
    "br": "Eva Airways",
    "eva airways": "Eva Airways",
    "delta": "Delta Air",
    "dl": "Delta Air",
    "delta air": "Delta Air",
    "delta air lines": "Delta Air",
    "delta airlines": "Delta Air",
    "uae": "Emirates Airline",
    "sia": "Singapore Airlines",
    "klm_eir": "KLM Airlines",
    # "arabia ?united",
    "saudi arabia": "Saudi",
    "dubklm100": "KLM Airlines",
    "flights": None,
    "retweet": None,
    "airlines": None,
    "airways": None,
    "american": "American Airlines",
    "aa": "American Airlines",
    "southwest": "Southwest",
    "wn": "Southwest",
    "spirit": "Spirit"
}
